# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBitWkzh035_By6eUKWjW4lssK94S9jy
"""

def laplacian_lazy(Z, periodic=1):

  import numpy as np

  if periodic == 1:
    south = np.roll(Z, shift=-1, axis=0)
    north = np.roll(Z, shift=1, axis=0)
    east = np.roll(Z, shift=-1, axis=1)
    west = np.roll(Z, shift=1, axis=1)
  else:
    south = np.pad(Z[1:, :], ((0, 1), (0, 0)), mode='constant')
    north = np.pad(Z[: -1, :], ((1, 0), (0, 0)), mode='constant')
    east = np.pad(Z[:, 1:], ((0, 0), (0, 1)), mode='constant')
    west = np.pad(Z[:, : -1], ((0, 0), (1, 0)), mode='constant')

  Zav = 0.5 * Z + 0.125 * (north + south + east + west)
  return Zav

def noise_generator(N, beta, D, samples):

  import numpy as np

# Generates an array (samples x N x D x D) containing the matrices of disorder for every time

  noise=[]
  for k in range(samples):
    noise_current=[]
    for i in range(N):
      lognorm = np.random.lognormal(mean=-0.5 * (beta**2), sigma=beta, size=(D, D))
      noise_current.append(lognorm)
      noise.append(noise_current)
  return np.array(noise)

def zeta(
  N,
  samples,
  beta,
  noise,
  periodic,
  normalized=True,
  r0=0,
  range_val=0.0,
  full=False,
):

  import numpy as np
  import time

  # Check that N is even
  if N % 2 != 0 or N < 0:
    raise ValueError("N must be positive and even")

  # Check that samples is a positive integer
  if samples % 1 != 0 or samples < 0:
    raise ValueError("samples must be a positive integer")
  samples = int(samples)

  # Check that periodic is either 0 or 1
  if periodic != 0 and periodic != 1:
    raise ValueError("periodic must be 0 or 1")

  # Check that normalized is either 0 or 1
  if normalized != 0 and normalized != 1:
    raise ValueError("normalized must be 0 or 1")

  # Check that both range_val and r0 are nonnegative
  if range_val < 0 or r0 < 0:
    raise ValueError("range and r0 cannot be negative")

  # Check that beta is non-negative
  if beta < 0:
    raise ValueError("beta cannot be negative")

  # --------------------

  # Record parameters in a string
  parameters = (
    f"N = {N:.0e}"
    f"(r0 = {round(r0, 1)}, range = {round(range_val, 1)})"
  )

  # Define the space dimensions
  supp = min(int((range_val + r0) * np.sqrt(N)), N // 2) # half ofthe square size
  D = 2 * supp + 1 # number of integer points in the square side
  I_idx = supp # center of the square side

  # Labels for rows and columns
  row_names = np.arange(-supp, supp + 1, 1)
  col_names = row_names

  # ZZ is an array (samples x D x D) holding the final state of zeta for each sample
  ZZ = []

  # ZZ_full is an array (samples x time_steps x D x D) holding the state of zeta for each time step and sample
  ZZ_full = []

  # Compute of the partition function
  for k in range(samples):
    start_time = time.time()

    # ZZ_full_current holds each state of zeta for the current sample
    ZZ_full_current = []

    # Initialize Z to 1 in the box B = { -r0 sqrt{N}, ..., r0 sqrt{N}}ˆ2
    Z = np.zeros((D, D))
    supp0 = min(int(r0 * np.sqrt(N)), N // 2)

    dom0_start = I_idx - supp0
    dom0_end = I_idx + supp0 + 1
    D0 = 2 * supp0 + 1
    Z[dom0_start:dom0_end, dom0_start:dom0_end] = 1.0

    if full:
      ZZ_full_current.append(Z.copy())

    # Compute the partition function for the current sample
    for i in range(N):
      Zav = laplacian_lazy(Z,periodic)
      Z = noise[k][i] * Zav

      # Preparing the current Z state for appending to ZZ_full_current
      Z_state = Z.copy()

      if normalized:
        Z_state /= (D0**2)

      # Append to ZZ_full_current
      if full:
        ZZ_full_current.append(Z_state)

    # Store the final state of Z for the current sample in ZZ
    if not normalized:
      ZZ.append(Z.copy())
    else:
      ZZ.append(Z.copy() / (D0**2))

    # Record execution time
    end_time = time.time()
    time_taken = round(end_time - start_time, 2)

    print(f"Sample {k + 1} produced")
    print(f"{time_taken} seconds\n")

    # Append the collected frames for the current sample to ZZ_full
    if full:
      ZZ_full.append(ZZ_full_current)

  print("Done.")

  # Return the output
  output = {"data": ZZ, "row_names": row_names, "col_names": col_names,"parameters": parameters}
  if full:
    output["ZZ_full"] = ZZ_full

  return output

def zeta_inverse(
  N,
  samples,
  beta,
  noise,
  periodic,
  normalized=True,
  r0=0,
  range_val=0.0,
  full=False,
):

  import numpy as np
  import time

  # Check that N is even
  if N % 2 != 0 or N < 0:
    raise ValueError("N must be positive and even")

  # Check that samples is a positive integer
  if samples % 1 != 0 or samples < 0:
    raise ValueError("samples must be a positive integer")
  samples = int(samples)

  # Check that periodic is either 0 or 1
  if periodic != 0 and periodic != 1:
    raise ValueError("periodic must be 0 or 1")

  # Check that normalized is either 0 or 1
  if normalized != 0 and normalized != 1:
    raise ValueError("normalized must be 0 or 1")

  # Check that both range_val and r0 are nonnegative
  if range_val < 0 or r0 < 0:
    raise ValueError("range and r0 cannot be negative")

  # Check that beta is non-negative
  if beta < 0:
    raise ValueError("beta cannot be negative")

  # --------------------

  # Record parameters in a string
  parameters = (
    f"N = {N:.0e}"
    f"(r0 = {round(r0, 1)}, range = {round(range_val, 1)})"
  )

  # Define the space dimensions
  supp = min(int((range_val + r0) * np.sqrt(N)), N // 2) # half ofthe square size
  D = 2 * supp + 1 # number of integer points in the square side
  I_idx = supp # center of the square side

  # Labels for rows and columns
  row_names = np.arange(-supp, supp + 1, 1)
  col_names = row_names

  # ZZ is an array (samples x D x D) holding the final state of zeta for each sample
  ZZ_inv = []

  # ZZ_full is an array (samples x time_steps x D x D) holding the state of zeta for each time step and sample
  ZZ_full_inv = []

  # Compute of the partition function
  for k in range(samples):
    start_time = time.time()

    # ZZ_full_current holds each state of zeta for the current sample
    ZZ_full_inv_current = []

    # Initialize Z to 1 in the box B = { -r0 sqrt{N}, ..., r0 sqrt{N}}ˆ2
    Z = np.ones((D, D))

    if full:
      ZZ_full_inv_current.append(Z.copy())

    # Compute D0 for normalization
    supp0 = min(int(r0 * np.sqrt(N)), N // 2)
    dom0_start = I_idx - supp0
    dom0_end = I_idx + supp0 + 1
    D0 = 2 * supp0 + 1

    # Compute the partition function for the current sample
    for i in range(N):
      # Noise first, then laplacian
      w = noise[k][-i-1]
      Z = laplacian_lazy(w*Z,periodic)

      # Preparing the current Z state for appending to ZZ_full_current
      Z_state = Z.copy()

      if normalized:
        Z_state /= (D0**2)

      # Append to ZZ_full_current
      if full:
        ZZ_full_inv_current.append(Z_state)

    # Store the final state of Z for the current sample in ZZ
    if not normalized:
      ZZ_inv.append(Z.copy())
    else:
      ZZ_inv.append(Z.copy() / (D0**2))

    # Record execution time
    end_time = time.time()
    time_taken = round(end_time - start_time, 2)

    print(f"Sample {k + 1} produced")
    print(f"{time_taken} seconds\n")

    # Append the collected frames for the current sample to ZZ_full_inv
    # Note that the states are collected in reverse order with respect to zeta (forward)
    if full:
      ZZ_full_inv.append(ZZ_full_inv_current)

  print("Done.")

  # Return the output
  output = {"data": ZZ_inv, "row_names": row_names, "col_names": col_names,"parameters": parameters}
  if full:
    output["ZZ_full_inverse"] = ZZ_full_inv

  return output

def path_probability(
  N,
  samples,
  beta,
  noise,
  periodic,
  normalized=1,
  r0=3.0,
  range_val=0.0,
):

  import numpy as np

  output = zeta(
    N=N,
    samples=samples,
    beta=beta,
    noise=noise,
    r0=r0,
    range_val=range_val,
    periodic=periodic,
    normalized=normalized,
    full=True,
  )

  # Extract data and metadata
  zeta_data = output['data']
  row_names = output['row_names']
  col_names = output['col_names']
  parameters = output['parameters']
  ZZ_full = output['ZZ_full']
  print(f"Parameters: {parameters}")
  print(f"Shape of zeta_data: {np.array(zeta_data).shape}")
  print(f"Length of ZZ_full: {len(ZZ_full)}")
  print(f"Number of samples in ZZ_full: {len(ZZ_full)}")

  # Do the same for zeta_inverse
  output_inverse = zeta_inverse(
    N=N,
    samples=samples,
    beta=beta,
    noise=noise,
    r0=r0,
    range_val=range_val,
    periodic=periodic,
    normalized=normalized,
    full=True,
  )

  zeta_data_inverse = output_inverse['data']
  row_names = output_inverse['row_names']
  col_names = output_inverse['col_names']
  parameters_inverse = output_inverse['parameters']
  ZZ_full_inverse = output_inverse['ZZ_full_inverse']

  print(f"Parameters: {parameters_inverse}")
  print(f"Shape of zeta_data_inverse: {np.array(zeta_data_inverse).shape}")
  print(f"Number of samples in ZZ_full_inverse: {len(ZZ_full_inverse)}")

  # Compute path probability P_N(S_M = x) for each 0 <= M <= N
  # path_probability is an array (samples x M_steps x D x D) holding the path probability at each time step and sample
  path_probability = []

  for k in range(samples):
    path_probability_current = []

    for M in range(len(ZZ_full[k])):
      numerator = ZZ_full[k][M] * ZZ_full_inverse[k][len(ZZ_full[k])-M-1]
      denominator = np.sum(numerator)

      if denominator == 0:
        polymer_measure = np.zeros_like(numerator)
      else:
        polymer_measure = numerator / denominator

      path_probability_current.append(polymer_measure)

    path_probability.append(path_probability_current)

  print(f"Shape of path_probability: {np.array(path_probability).shape}")

  # Return the output
  return {"path_probability": np.array(path_probability), "row_names": row_names, "col_names": col_names, "parameters": parameters}